/**
 * Academic Timetable & Course Dataset
 * Parsed from Slot System_Aug 2026.docx and department course allocation spreadsheets.
 */

export interface Course {
  id: string;
  code: string;
  name: string;
  slot: string;
  hall: string;
  faculty: string;
  program: string;
  semester: string;
  sourceFile: string;
}

export type ProgramType =
  | 'B.Tech CSE'
  | 'B.Tech ECE'
  | 'B.Tech ME'
  | 'B.Tech EP'
  | 'B.Tech SIDI'
  | 'B.Tech SM'
  | 'Dual Degree CSE (AI)'
  | 'Dual Degree ECE (VLSI)'
  | 'Dual Degree ME (AI&R)'
  | 'Common (First Sem)';

export type SemesterType = 'Semester 1' | 'Semester 3' | 'Semester 5' | 'Semester 7';

export const PROGRAM_OPTIONS: ProgramType[] = [
  'B.Tech CSE',
  'B.Tech ECE',
  'B.Tech ME',
  'B.Tech EP',
  'B.Tech SIDI',
  'B.Tech SM',
  'Dual Degree CSE (AI)',
  'Dual Degree ECE (VLSI)',
  'Dual Degree ME (AI&R)',
  'Common (First Sem)',
];

export const SEMESTER_OPTIONS: SemesterType[] = [
  'Semester 1',
  'Semester 3',
  'Semester 5',
  'Semester 7',
];

/** Slot Schedule Matrix (Higher Semesters) */
export const HIGHER_SEM_SLOTS: Record<string, Record<string, string>> = {
  MON: {
    '8:00 - 8:50 AM': 'A',
    '9:00 - 9:50 AM': 'F',
    '10:00 - 10:50 AM': 'D',
    '11:00 - 11:50 AM': 'B',
    '12:00 - 12:50 PM': 'G',
    '1:00 - 1:50 PM': 'Lunch',
    '2:00 - 2:50 PM': 'H1',
    '3:00 - 3:50 PM': 'H2',
    '4:00 - 4:50 PM': 'H3',
    '5:00 - 5:50 PM': 'X1',
    '6:15 - 7:00 PM': 'NSO / NCC',
  },
  TUE: {
    '8:00 - 8:50 AM': 'B',
    '9:00 - 9:50 AM': 'G',
    '10:00 - 10:50 AM': 'E',
    '11:00 - 11:50 AM': 'C',
    '12:00 - 12:50 PM': 'A',
    '1:00 - 1:50 PM': 'Lunch',
    '2:00 - 2:50 PM': 'I1',
    '3:00 - 3:50 PM': 'I2',
    '4:00 - 4:50 PM': 'I3',
    '5:00 - 5:50 PM': 'X2',
  },
  WED: {
    '8:00 - 8:50 AM': 'C',
    '9:00 - 9:50 AM': 'A',
    '10:00 - 10:50 AM': 'F',
    '11:00 - 11:50 AM': 'D',
    '12:00 - 12:50 PM': 'B',
    '1:00 - 1:50 PM': 'Lunch',
    '2:00 - 2:50 PM': 'J1',
    '3:00 - 3:50 PM': 'J2',
    '4:00 - 4:50 PM': 'J3',
    '5:00 - 5:50 PM': 'X3',
  },
  THU: {
    '8:00 - 8:50 AM': 'D',
    '9:00 - 9:50 AM': 'B',
    '10:00 - 10:50 AM': 'G',
    '11:00 - 11:50 AM': 'E',
    '12:00 - 12:50 PM': 'C',
    '1:00 - 1:50 PM': 'Lunch',
    '2:00 - 2:50 PM': 'K1',
    '3:00 - 3:50 PM': 'K2',
    '4:00 - 4:50 PM': 'K3',
    '5:00 - 5:50 PM': 'X4',
  },
  FRI: {
    '8:00 - 8:50 AM': 'E',
    '9:00 - 9:50 AM': 'C',
    '10:00 - 10:50 AM': 'A',
    '11:00 - 11:50 AM': 'F',
    '12:00 - 12:50 PM': 'D',
    '1:00 - 1:50 PM': 'Lunch',
    '2:00 - 2:50 PM': 'L1',
    '3:00 - 3:50 PM': 'L2',
    '4:00 - 4:50 PM': 'L3',
    '5:00 - 5:50 PM': 'X5',
  },
};

/** Slot Schedule Matrix (First Semester) */
export const FIRST_SEM_SLOTS: Record<string, Record<string, string>> = {
  MON: {
    '8:00 - 8:50 AM': 'A',
    '9:00 - 9:50 AM': 'F',
    '10:00 - 10:50 AM': 'D',
    '11:00 - 11:50 AM': 'B',
    '12:00 - 12:50 PM': 'Lunch',
    '1:00 - 1:50 PM': 'H1',
    '2:00 - 2:50 PM': 'H2',
    '3:20 - 4:10 PM': 'H3',
    '4:20 - 5:10 PM': 'H4',
    '5:00 - 5:50 PM': 'X1',
  },
  TUE: {
    '8:00 - 8:50 AM': 'B',
    '9:00 - 9:50 AM': 'G',
    '10:00 - 10:50 AM': 'E',
    '11:00 - 11:50 AM': 'C',
    '12:00 - 12:50 PM': 'Lunch',
    '1:00 - 1:50 PM': 'I1',
    '2:00 - 2:50 PM': 'I2',
    '3:20 - 4:10 PM': 'I3',
    '4:20 - 5:10 PM': 'I4',
    '5:00 - 5:50 PM': 'X2',
  },
  WED: {
    '8:00 - 8:50 AM': 'C',
    '9:00 - 9:50 AM': 'A',
    '10:00 - 10:50 AM': 'F',
    '11:00 - 11:50 AM': 'D',
    '12:00 - 12:50 PM': 'Lunch',
    '1:00 - 1:50 PM': 'J1',
    '2:00 - 2:50 PM': 'J2',
    '3:20 - 4:10 PM': 'J3',
    '4:20 - 5:10 PM': 'J4',
    '5:00 - 5:50 PM': 'X3',
  },
  THU: {
    '8:00 - 8:50 AM': 'D',
    '9:00 - 9:50 AM': 'B',
    '10:00 - 10:50 AM': 'G',
    '11:00 - 11:50 AM': 'E',
    '12:00 - 12:50 PM': 'Lunch',
    '1:00 - 1:50 PM': 'K1',
    '2:00 - 2:50 PM': 'K2',
    '3:20 - 4:10 PM': 'K3',
    '4:20 - 5:10 PM': 'K4',
    '5:00 - 5:50 PM': 'X4',
  },
  FRI: {
    '8:00 - 8:50 AM': 'E',
    '9:00 - 9:50 AM': 'C',
    '10:00 - 10:50 AM': 'A',
    '11:00 - 11:50 AM': 'F',
    '12:00 - 12:50 PM': 'Lunch',
    '1:00 - 1:50 PM': 'L1',
    '2:00 - 2:50 PM': 'L2',
    '3:20 - 4:10 PM': 'L3',
    '4:20 - 5:10 PM': 'L4',
    '5:00 - 5:50 PM': 'X5',
  },
};

export const ALL_COURSES: Course[] = [
  {
    "id": "25MA1000-74",
    "code": "25MA1000",
    "name": "Calculus (3 1 0 4)",
    "slot": "B, J3",
    "hall": "H21",
    "faculty": "Dr.\u00a0 M Subramani",
    "program": "Common (First Sem)",
    "semester": "Semester 1",
    "sourceFile": "First sem-Aug 2026.xlsx"
  },
  {
    "id": "25PH1000-75",
    "code": "25PH1000",
    "name": "Physics for Engineers (3 0 2 4)",
    "slot": "F / I1, I2",
    "hall": "H21 / L117",
    "faculty": "Dr. Y. Ashok Kumar Reddy",
    "program": "Common (First Sem)",
    "semester": "Semester 1",
    "sourceFile": "First sem-Aug 2026.xlsx"
  },
  {
    "id": "25EC1000-76",
    "code": "25EC1000",
    "name": "Basic Electrical Engineering (3 1 0 4)",
    "slot": "D, I3",
    "hall": "H21",
    "faculty": "Dr B. Chitti Babu",
    "program": "Common (First Sem)",
    "semester": "Semester 1",
    "sourceFile": "First sem-Aug 2026.xlsx"
  },
  {
    "id": "25CS1000-77",
    "code": "25CS1000",
    "name": "Problem Solving and Programming (3 0 2 4)",
    "slot": "C, A (Mon) / E+C (Fri)",
    "hall": "H21 / L209",
    "faculty": "Dr Noor Mahammad",
    "program": "Common (First Sem)",
    "semester": "Semester 1",
    "sourceFile": "First sem-Aug 2026.xlsx"
  },
  {
    "id": "25DS1000-78",
    "code": "25DS1000",
    "name": "Concepts in Engineering Design (2 0 2 3)",
    "slot": "G / J1, J2",
    "hall": "H21",
    "faculty": "Dr. Rino",
    "program": "Common (First Sem)",
    "semester": "Semester 1",
    "sourceFile": "First sem-Aug 2026.xlsx"
  },
  {
    "id": "25HS1000-79",
    "code": "25HS1000",
    "name": "Effective Language and Communication Skills (1 0 2 2)",
    "slot": "A (Wed) / K1, K2",
    "hall": "L209 / H21",
    "faculty": "Dr. Parvathy Das",
    "program": "Common (First Sem)",
    "semester": "Semester 1",
    "sourceFile": "First sem-Aug 2026.xlsx"
  },
  {
    "id": "25ME1000-80",
    "code": "25ME1000",
    "name": "Engineering Skills Practice (0 0 2 1)",
    "slot": "L1, L2",
    "hall": "L013",
    "faculty": "Dr Pilgar C. M.",
    "program": "Common (First Sem)",
    "semester": "Semester 1",
    "sourceFile": "First sem-Aug 2026.xlsx"
  },
  {
    "id": "25PH2000-81",
    "code": "25PH2000",
    "name": "Mathematical Physics",
    "slot": "E",
    "hall": "H21",
    "faculty": "Dr. Sai Prashanth",
    "program": "B.Tech EP",
    "semester": "Semester 3",
    "sourceFile": "EP_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-82",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G",
    "hall": "H25",
    "faculty": "Dr Rahul Raman",
    "program": "B.Tech EP",
    "semester": "Semester 3",
    "sourceFile": "EP_Aug 2026.xlsx"
  },
  {
    "id": "25EC2000-83",
    "code": "25EC2000",
    "name": "Electronic Devices and Circuits (with ECE)",
    "slot": "B",
    "hall": "H02",
    "faculty": "Dr. Pandiyarasan Veluswamy",
    "program": "B.Tech EP",
    "semester": "Semester 3",
    "sourceFile": "EP_Aug 2026.xlsx"
  },
  {
    "id": "25EC2001-84",
    "code": "25EC2001",
    "name": "Digital Circuit Design (with ECE)",
    "slot": "D",
    "hall": "H02",
    "faculty": "Dr. S. Kalpana",
    "program": "B.Tech EP",
    "semester": "Semester 3",
    "sourceFile": "EP_Aug 2026.xlsx"
  },
  {
    "id": "25PH2001-85",
    "code": "25PH2001",
    "name": "General Physics",
    "slot": "A / H1, H2",
    "hall": "H21 / L117",
    "faculty": "Dr. Manjusha Battabyal",
    "program": "B.Tech EP",
    "semester": "Semester 3",
    "sourceFile": "EP_Aug 2026.xlsx"
  },
  {
    "id": "25EC2002-86",
    "code": "25EC2002",
    "name": "Signals and Systems (with ECE)",
    "slot": "C",
    "hall": "H02",
    "faculty": "Dr. R Sri Prakash",
    "program": "B.Tech EP",
    "semester": "Semester 3",
    "sourceFile": "EP_Aug 2026.xlsx"
  },
  {
    "id": "25EC2004-87",
    "code": "25EC2004",
    "name": "Digital Circuit Design Practice (with ECE)",
    "slot": "J",
    "hall": "L214",
    "faculty": "Dr. Sundeep Kumar",
    "program": "B.Tech EP",
    "semester": "Semester 3",
    "sourceFile": "EP_Aug 2026.xlsx"
  },
  {
    "id": "25EC2003-88",
    "code": "25EC2003",
    "name": "Electronic Devices and Circuits Practice (with ECE)",
    "slot": "I",
    "hall": "L217",
    "faculty": "Dr. K. P. Pradhan",
    "program": "B.Tech EP",
    "semester": "Semester 3",
    "sourceFile": "EP_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-89",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H26",
    "faculty": "Dr. Samriddho Roy",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-90",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G",
    "hall": "H45",
    "faculty": "Dr Nisanth Kartheek",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS2000-91",
    "code": "25DS2000",
    "name": "Mechanics and Mechanisms",
    "slot": "B / I1, I2",
    "hall": "H33 / L612",
    "faculty": "Dr. Raguraman",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS2001-92",
    "code": "25DS2001",
    "name": "Instrumentation and Control systems",
    "slot": "A / H1, H2",
    "hall": "H33 / L614",
    "faculty": "Dr. Srikar",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS2002-93",
    "code": "25DS2002",
    "name": "Sociology of Design",
    "slot": "C / K1, K2",
    "hall": "H33",
    "faculty": "Dr. Rino",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS2003-94",
    "code": "25DS2003",
    "name": "Human Centered Design",
    "slot": "D / J1, J2",
    "hall": "H33",
    "faculty": "Dr. Arunachalam",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS2004-95",
    "code": "25DS2004",
    "name": "Techno-asthetics in Product Detailing",
    "slot": "F / L1, L2",
    "hall": "H33 / L407B",
    "faculty": "Dr. Siddhant",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS5000-96",
    "code": "25DS5000",
    "name": "Foundation for integrated product design",
    "slot": "Full ID26M1",
    "hall": "Full ID26M1",
    "faculty": "Dr Sudhir",
    "program": "B.Tech SIDI",
    "semester": "Semester 1",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS5001-97",
    "code": "25DS5001",
    "name": "Aesthetics, Forms and Sketching",
    "slot": "Tuesday 10 am to 1 pm",
    "hall": "L409A",
    "faculty": "Dr. Narendran",
    "program": "B.Tech SIDI",
    "semester": "Semester 1",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS5002-98",
    "code": "25DS5002",
    "name": "Design, Technology and Society",
    "slot": "Monday 10 am to 1 pm",
    "hall": "L409A",
    "faculty": "Mr. VSS Iyer",
    "program": "B.Tech SIDI",
    "semester": "Semester 1",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS5003-99",
    "code": "25DS5003",
    "name": "Design Research: Theory and Methods",
    "slot": "Wednesday 10 am to 1 pm",
    "hall": "L409A",
    "faculty": "Dr. Bingi & Dr. Anudeep",
    "program": "B.Tech SIDI",
    "semester": "Semester 1",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS5004-100",
    "code": "25DS5004",
    "name": "Material selection for product designers",
    "slot": "Thursday 10 am to 1 pm",
    "hall": "L409A",
    "faculty": "Dr. Sadhasivam",
    "program": "B.Tech SIDI",
    "semester": "Semester 1",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS5005-101",
    "code": "25DS5005",
    "name": "Design Realization Skills Practice",
    "slot": "Monday 2 to 5 pm",
    "hall": "L409A",
    "faculty": "Dr. Karthik C/Mr. Murugadoss",
    "program": "B.Tech SIDI",
    "semester": "Semester 1",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS5006-102",
    "code": "25DS5006",
    "name": "Visual Communication Design",
    "slot": "Friday 10 am to 1 pm",
    "hall": "L409A",
    "faculty": "Dr. Arunachalam",
    "program": "B.Tech SIDI",
    "semester": "Semester 1",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS5007-103",
    "code": "25DS5007",
    "name": "Concept Design Project",
    "slot": "Tuesday and Friday 2 to 5 pm",
    "hall": "L612",
    "faculty": "Dr. Monisha",
    "program": "B.Tech SIDI",
    "semester": "Semester 1",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS6000-104",
    "code": "25DS6000",
    "name": "Capstone Project",
    "slot": "Full ID25M1",
    "hall": "Full ID25M1",
    "faculty": "Dr Bingi",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS6001-105",
    "code": "25DS6001",
    "name": "Strategic Management of Design and Innovation",
    "slot": "Online",
    "hall": "Online",
    "faculty": "Dr. Sudhir V & Dr. Rajnish",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25DS6002-106",
    "code": "25DS6002",
    "name": "Sustainable Product Service Systems",
    "slot": "Online",
    "hall": "Online",
    "faculty": "Dr Srikar",
    "program": "B.Tech SIDI",
    "semester": "Semester 3",
    "sourceFile": "SIDI_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-107",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H23",
    "faculty": "Dr. Subhasis Ghora",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-108",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H24",
    "faculty": "Dr. Jagannath Bhanja",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-109",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H26",
    "faculty": "Dr. Samriddho Roy",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-110",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G,(A+F-Wednesday)",
    "hall": "H15,L509,L507",
    "faculty": "Dr Preeth",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-111",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G,(A+F-Wednesday)",
    "hall": "H25,L515,512",
    "faculty": "Dr Rahul Raman",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2000-112",
    "code": "25EC2000",
    "name": "Electronic Devices and Circuits",
    "slot": "B",
    "hall": "H43",
    "faculty": "Dr. Tejendra Dixit",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2000-113",
    "code": "25EC2000",
    "name": "Electronic Devices and Circuits",
    "slot": "B",
    "hall": "H02",
    "faculty": "Dr. Pandiyarasan Veluswamy",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2001-114",
    "code": "25EC2001",
    "name": "Digital Circuit Design",
    "slot": "D",
    "hall": "H43",
    "faculty": "Dr. Gowri A",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2001-115",
    "code": "25EC2001",
    "name": "Digital Circuit Design",
    "slot": "D",
    "hall": "H02",
    "faculty": "Dr. S Kalpana",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2002-116",
    "code": "25EC2002",
    "name": "Signals and Systems",
    "slot": "C",
    "hall": "H43",
    "faculty": "Dr. Rohini",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2002-117",
    "code": "25EC2002",
    "name": "Signals and Systems",
    "slot": "C",
    "hall": "H02",
    "faculty": "Dr. R Sri Prakash",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2004-118",
    "code": "25EC2004",
    "name": "Digital Circuit Design Practice",
    "slot": "H",
    "hall": "L214",
    "faculty": "Dr. Gowri A",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2004-119",
    "code": "25EC2004",
    "name": "Digital Circuit Design Practice",
    "slot": "I",
    "hall": "L214",
    "faculty": "Dr. S Kalpana",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2003-120",
    "code": "25EC2003",
    "name": "Electronic Devices and Circuits Practice",
    "slot": "J",
    "hall": "L217",
    "faculty": "Dr. Tejendra Dixit",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2003-121",
    "code": "25EC2003",
    "name": "Electronic Devices and Circuits Practice",
    "slot": "H",
    "hall": "L217",
    "faculty": "Dr. Pandiyarasan Veluswamy",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-122",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H26",
    "faculty": "Dr. Samriddho Roy",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-123",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G",
    "hall": "H25",
    "faculty": "Dr Rahul Raman",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2000-124",
    "code": "25EC2000",
    "name": "Electronic Devices and Circuits",
    "slot": "B",
    "hall": "H02",
    "faculty": "Dr. Pandiyarasan Veluswamy",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2001-125",
    "code": "25EC2001",
    "name": "Digital Circuit Design",
    "slot": "D",
    "hall": "H02",
    "faculty": "Dr. S Kalpana",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2002-126",
    "code": "25EC2002",
    "name": "Signals and Systems",
    "slot": "C",
    "hall": "H02",
    "faculty": "Dr. R Sri Prakash",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2004-127",
    "code": "25EC2004",
    "name": "Digital Circuit Design Practice",
    "slot": "J",
    "hall": "L214",
    "faculty": "Dr. Sundeep Kumar",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2003-128",
    "code": "25EC2003",
    "name": "Electronic Devices and Circuits Practice",
    "slot": "I",
    "hall": "L217",
    "faculty": "Dr. K. P. Pradhan",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-129",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H26",
    "faculty": "Dr. Samriddho Roy",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-130",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G",
    "hall": "H25",
    "faculty": "Dr Rahul Raman",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2000-131",
    "code": "25EC2000",
    "name": "Electronic Devices and Circuits",
    "slot": "B",
    "hall": "H02",
    "faculty": "Dr. Pandiyarasan Veluswamy",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2001-132",
    "code": "25EC2001",
    "name": "Digital Circuit Design",
    "slot": "D",
    "hall": "H02",
    "faculty": "Dr. S Kalpana",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2002-133",
    "code": "25EC2002",
    "name": "Signals and Systems",
    "slot": "C",
    "hall": "H02",
    "faculty": "Dr. R Sri Prakash",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2004-134",
    "code": "25EC2004",
    "name": "Digital Circuit Design Practice",
    "slot": "J",
    "hall": "L214",
    "faculty": "Dr. Sundeep Kumar",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC2003-135",
    "code": "25EC2003",
    "name": "Electronic Devices and Circuits Practice",
    "slot": "I",
    "hall": "L217",
    "faculty": "Dr. K. P. Pradhan",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "CS3006-136",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "E,I1,I2",
    "hall": "H42, L209,L515",
    "faculty": "Dr S Vijayakumar (Batch 1)",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "CS3006-137",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "B,I1,I2",
    "hall": "H42,L209,L515",
    "faculty": "Dr S Vijayakumar (Batch 2)",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "DS3000-138",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H04",
    "faculty": "Dr. Sudhir V",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "DS3000-139",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H05",
    "faculty": "Dr. Shanmugam",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3000-140",
    "code": "EC3000",
    "name": "Control Systems",
    "slot": "B",
    "hall": "H11",
    "faculty": "Dr. K. Selvajyothi",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3000-141",
    "code": "EC3000",
    "name": "Control Systems",
    "slot": "D",
    "hall": "H12",
    "faculty": "Dr. Uttam Pal",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3001-142",
    "code": "EC3001",
    "name": "Communication Systems",
    "slot": "D",
    "hall": "H11",
    "faculty": "Dr. Premkumar K",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3001-143",
    "code": "EC3001",
    "name": "Communication Systems",
    "slot": "E,X3",
    "hall": "H12",
    "faculty": "Dr. Badri",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3002-144",
    "code": "EC3002",
    "name": "Digital Signal Processing Practice",
    "slot": "K",
    "hall": "L309",
    "faculty": "Dr. Srijith",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3002-145",
    "code": "EC3002",
    "name": "Digital Signal Processing Practice",
    "slot": "L",
    "hall": "L309",
    "faculty": "Dr. Rohini",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3002-146",
    "code": "EC3002",
    "name": "Digital Signal Processing Practice",
    "slot": "J",
    "hall": "L309",
    "faculty": "Dr. Priyanka Kokil",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3003-147",
    "code": "EC3003",
    "name": "Analog Circuits Practice",
    "slot": "J",
    "hall": "L210",
    "faculty": "Prof. Binsu J Kailath",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3003-148",
    "code": "EC3003",
    "name": "Analog Circuits Practice",
    "slot": "K",
    "hall": "L210",
    "faculty": "Dr. S Kalpana",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3003-149",
    "code": "EC3003",
    "name": "Analog Circuits Practice",
    "slot": "L",
    "hall": "L210",
    "faculty": "Dr. Tejendra Dixit",
    "program": "B.Tech ECE",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "CS3006-150",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "B, I1, I2",
    "hall": "H42,L209,L515",
    "faculty": "Dr S Vijayakumar (Batch 2)",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "DS3000-151",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H05",
    "faculty": "Dr. Shanmugam",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "DS3000-152",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H15",
    "faculty": "Dr. Suresh V",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3000-153",
    "code": "EC3000",
    "name": "Control Systems",
    "slot": "D",
    "hall": "H12",
    "faculty": "Dr. Uttam Pal",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3001-154",
    "code": "EC3001",
    "name": "Communication Systems",
    "slot": "E,X3",
    "hall": "H12",
    "faculty": "Dr. Badri",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3002-155",
    "code": "EC3002",
    "name": "Digital Signal Processing Practice",
    "slot": "J",
    "hall": "L309",
    "faculty": "Dr. Priyanka Kokil",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3003-156",
    "code": "EC3003",
    "name": "Analog Circuits Practice",
    "slot": "L",
    "hall": "L210",
    "faculty": "Dr. Tejendra Dixit",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "CS3006-157",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "B, I1, I2",
    "hall": "H42,L209,L515",
    "faculty": "Dr S Vijayakumar (Batch 2)",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "DS3000-158",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H15",
    "faculty": "Dr. Suresh V",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3000-159",
    "code": "EC3000",
    "name": "Control Systems",
    "slot": "D",
    "hall": "H12",
    "faculty": "Dr. Uttam Pal",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3001-160",
    "code": "EC3001",
    "name": "Communication Systems",
    "slot": "E,X3",
    "hall": "H12",
    "faculty": "Dr. Badri",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3002-161",
    "code": "EC3002",
    "name": "Digital Signal Processing Practice",
    "slot": "J",
    "hall": "L309",
    "faculty": "Dr. Priyanka Kokil",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC3003-162",
    "code": "EC3003",
    "name": "Analog Circuits Practice",
    "slot": "L",
    "hall": "L210",
    "faculty": "Dr. Tejendra Dixit",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 5",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC5028-163",
    "code": "EC5028",
    "name": "Mathematics for Communication",
    "slot": "A",
    "hall": "H14",
    "faculty": "Dr. Badri",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC5029-164",
    "code": "EC5029",
    "name": "Modeling and Simulation",
    "slot": "C,L",
    "hall": "H14,L211",
    "faculty": "Dr. Premkumar K",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC5030-165",
    "code": "EC5030",
    "name": "Data Communication Networks",
    "slot": "G,X5",
    "hall": "H16",
    "faculty": "Dr. R Sri Prakash",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC5032-166",
    "code": "EC5032",
    "name": "Data Communication Networks Practice",
    "slot": "K",
    "hall": "L211",
    "faculty": "Dr. R Sri Prakash",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC5014-167",
    "code": "EC5014",
    "name": "Digital IC Design",
    "slot": "A",
    "hall": "H16",
    "faculty": "Prof. Binsu J Kailath",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC5009-168",
    "code": "EC5009",
    "name": "MOSFET Modeling for VLSI Circuits",
    "slot": "D",
    "hall": "H16",
    "faculty": "Dr. K. P. Pradhan",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC5011-169",
    "code": "EC5011",
    "name": "VLSI Testing and Testable Design",
    "slot": "C",
    "hall": "H16",
    "faculty": "Sh. Hariharan Seshadri",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC5033-170",
    "code": "EC5033",
    "name": "Device Modeling and Simulation Practice",
    "slot": "H",
    "hall": "L210",
    "faculty": "Dr. K P Pradhan",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC5034-171",
    "code": "EC5034",
    "name": "VLSI Testing Practice",
    "slot": "I",
    "hall": "L210",
    "faculty": "Sh. Hariharan Seshadri",
    "program": "Dual Degree ECE (VLSI)",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5004-172",
    "code": "25EC5004",
    "name": "Random Processes",
    "slot": "B",
    "hall": "H14",
    "faculty": "Prof. M. D. Selvaraj",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5005-173",
    "code": "25EC5005",
    "name": "Advanced Digital Communication",
    "slot": "E,X3",
    "hall": "H14",
    "faculty": "Prof. M. D. Selvaraj",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5006-174",
    "code": "25EC5006",
    "name": "Advanced Digital Signal Processing",
    "slot": "D",
    "hall": "H14",
    "faculty": "Dr. Priyanka Kokil",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5007-175",
    "code": "25EC5007",
    "name": "Advanced Digital Communication Practice",
    "slot": "I",
    "hall": "L211",
    "faculty": "Prof. M. D. Selvaraj",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5008-176",
    "code": "25EC5008",
    "name": "Advanced Digital Signal Processing Practice",
    "slot": "H",
    "hall": "L309",
    "faculty": "Dr. Priyanka Kokil",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5000-177",
    "code": "25EC5000",
    "name": "MOS Modeling for VLSI Circuits",
    "slot": "D",
    "hall": "H16",
    "faculty": "Dr. K P Pradhan",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5001-178",
    "code": "25EC5001",
    "name": "VLSI System Design",
    "slot": "B",
    "hall": "H16",
    "faculty": "Dr. Yanamala Muni Reddy",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5002-179",
    "code": "25EC5002",
    "name": "VLSI Testing and Testable Design",
    "slot": "E,I",
    "hall": "H16,L210",
    "faculty": "Dr. Yanamala Muni Reddy",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5003-180",
    "code": "25EC5003",
    "name": "Device Modeling and Simulation Practice",
    "slot": "H",
    "hall": "L210",
    "faculty": "Dr. K P Pradhan",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5009-181",
    "code": "25EC5009",
    "name": "Advanced Microwave Engineering",
    "slot": "G,X5",
    "hall": "H14",
    "faculty": "Dr. Sreenath Reddy",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5010-182",
    "code": "25EC5010",
    "name": "Advanced EMFT",
    "slot": "E,X3",
    "hall": "H43",
    "faculty": "Dr. S. Yuvaraj",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC5011-183",
    "code": "25EC5011",
    "name": "Advanced Microwave Engineering Practice",
    "slot": "J",
    "hall": "L211/L212",
    "faculty": "Dr. S. Yuvaraj/Dr. Sreenath Reddy",
    "program": "B.Tech ECE",
    "semester": "Semester 1",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "EC4000-184",
    "code": "EC4000",
    "name": "BT-EC-Summer Internship",
    "slot": "Full EC23B1",
    "hall": "",
    "faculty": "Dr K Premkumar",
    "program": "B.Tech ECE",
    "semester": "Semester 7",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC6000-185",
    "code": "25EC6000",
    "name": "M Tech Dissertation (MTD) Phase I (CMS)",
    "slot": "Full EC26M1",
    "hall": "",
    "faculty": "Dr K Premkumar",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC6003-186",
    "code": "25EC6003",
    "name": "M Tech Dissertation (MTD) Phase I (MVS)",
    "slot": "Full EC26M2",
    "hall": "",
    "faculty": "Dr K Premkumar",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC6006-187",
    "code": "25EC6006",
    "name": "M Tech Dissertation (MTD) Phase I (RFM)",
    "slot": "Full EC26M3",
    "hall": "",
    "faculty": "Dr K Premkumar",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC6001-188",
    "code": "25EC6001",
    "name": "M Tech Dissertation (MTD) Phase II (CMS)",
    "slot": "Full EC26M1",
    "hall": "",
    "faculty": "Dr K Premkumar",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC6004-189",
    "code": "25EC6004",
    "name": "M Tech Dissertation (MTD) Phase II (MVS)",
    "slot": "Full EC26M2",
    "hall": "",
    "faculty": "Dr K Premkumar",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25EC6007-190",
    "code": "25EC6007",
    "name": "M Tech Dissertation (MTD) Phase II (RFM)",
    "slot": "Full EC26M3",
    "hall": "",
    "faculty": "Dr K Premkumar",
    "program": "B.Tech ECE",
    "semester": "Semester 3",
    "sourceFile": "ECE_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-236",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H27",
    "faculty": "Dr. Sarbendu Rakshkit",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-237",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G (Tue, Thus) / H1-H2",
    "hall": "H45 / L515, L507",
    "faculty": "Dr Nishant Kartheek",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2000-238",
    "code": "25ME2000",
    "name": "Engineering Thermodynamics",
    "slot": "C",
    "hall": "H34",
    "faculty": "Dr. Shubhankar Chakraborty",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2000-239",
    "code": "25ME2000",
    "name": "Engineering Thermodynamics",
    "slot": "C",
    "hall": "H35",
    "faculty": "Dr S Jayavel",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2001-240",
    "code": "25ME2001",
    "name": "Mechanics of Materials",
    "slot": "G (Mon), B (Tue, Wed, Thus)",
    "hall": "H45 (G Mon)/H34 (B Tue, Wed, Thus)",
    "faculty": "Dr. Siva Prasad A V S",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2001-241",
    "code": "25ME2001",
    "name": "Mechanics of Materials",
    "slot": "B",
    "hall": "H35",
    "faculty": "Dr. Arul Kumar M",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2002-242",
    "code": "25ME2002",
    "name": "Fluid Mechanics and Machinery",
    "slot": "A",
    "hall": "H34",
    "faculty": "Dr. Karthick S",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2002-243",
    "code": "25ME2002",
    "name": "Fluid Mechanics and Machinery",
    "slot": "F,X4",
    "hall": "H35",
    "faculty": "Dr Vikas Kumar",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2003-244",
    "code": "25ME2003",
    "name": "Casting, Forming and Joining",
    "slot": "D",
    "hall": "H34",
    "faculty": "Dr. Senthilkumaran K",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2004-245",
    "code": "25ME2004",
    "name": "Manufacturing Processes Practice",
    "slot": "I1 (Tutorial), I2-I3 (Practice)",
    "hall": "H34/L013",
    "faculty": "Dr. Senthilkumaran K",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2004-246",
    "code": "25ME2004",
    "name": "Manufacturing Processes Practice",
    "slot": "J1 (Tutorial), J2-J3 (Practice)",
    "hall": "H34/L013",
    "faculty": "Dr. Senthilkumaran K",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-247",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H26",
    "faculty": "Dr. Samriddho Roy",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-248",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H31",
    "faculty": "Dr. Dheeraj Goel",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-249",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G, AF for Lab (Wednesday)",
    "hall": "H25/ L512 and L515",
    "faculty": "Dr Rahul Raman",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-250",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G (Tue, Thus), H1-H2",
    "hall": "H45, L515 and L507",
    "faculty": "Dr Nishant Kartheek",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25CS2006-251",
    "code": "25CS2006",
    "name": "Database Management Systems",
    "slot": "A, L3-X5",
    "hall": "H36/L507",
    "faculty": "Dr. Pilgar C. M.",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2005-252",
    "code": "25ME2005",
    "name": "Applied Mechanics",
    "slot": "B",
    "hall": "H36",
    "faculty": "Prof. Jayabal K",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2003-253",
    "code": "25ME2003",
    "name": "Casting, Forming and Joining",
    "slot": "D",
    "hall": "H35",
    "faculty": "Dr. Avinash Kumar",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2006-254",
    "code": "25ME2006",
    "name": "Sensors and Controls",
    "slot": "C",
    "hall": "H36",
    "faculty": "Prof. B Raja",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2007-255",
    "code": "25ME2007",
    "name": "Production Drawing",
    "slot": "I, X2",
    "hall": "L507",
    "faculty": "Dr. Shahul Hamid Khan",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2004-256",
    "code": "25ME2004",
    "name": "Manufacturing Processes Practice",
    "slot": "K1/H1 (Tutorial), K2-K3/H2-H3 (Practice)",
    "hall": "H35/L013",
    "faculty": "Dr. Avinash Kumar",
    "program": "B.Tech SM",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-257",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H31",
    "faculty": "Dr. Dheeraj Goel",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25CS2000-258",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G (Tue, Thus), H1-H2",
    "hall": "H45, L515 and L507",
    "faculty": "Dr Nishant Kartheek",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2000-259",
    "code": "25ME2000",
    "name": "Engineering Thermodynamics",
    "slot": "C",
    "hall": "H35",
    "faculty": "Dr S Jayavel",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2001-260",
    "code": "25ME2001",
    "name": "Mechanics of Materials",
    "slot": "B",
    "hall": "H35",
    "faculty": "Dr. Arul Kumar M",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2002-261",
    "code": "25ME2002",
    "name": "Fluid Mechanics and Machinery",
    "slot": "F,X4",
    "hall": "H35",
    "faculty": "Dr Vikas Kumar",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2003-262",
    "code": "25ME2003",
    "name": "Casting, Forming and Joining",
    "slot": "D",
    "hall": "H35",
    "faculty": "Dr Avinash Kumar",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME2004-263",
    "code": "25ME2004",
    "name": "Manufacturing Processes Practice",
    "slot": "K1/L1 (Tutorial), K2-K3/L2-L3 (Practice)",
    "hall": "H35/L013",
    "faculty": "Dr Avinash Kumar",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "CS3006-264",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "B, L1-L2",
    "hall": "H42/L209+L515",
    "faculty": "Dr S Vijaya Kumar (Another Batch)",
    "program": "B.Tech ME",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "CS3006-265",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "E, I3-X2",
    "hall": "H45/L209+L515",
    "faculty": "Dr Pradeep Kumar",
    "program": "B.Tech ME",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "DS3000-266",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H15",
    "faculty": "Dr. Suresh V",
    "program": "B.Tech ME",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "DS3000-267",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H25",
    "faculty": "Mr. Gokul R",
    "program": "B.Tech ME",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3000-268",
    "code": "ME3000",
    "name": "Design of Machine Elements",
    "slot": "G, X3",
    "hall": "H04",
    "faculty": "Dr. Venkata Timmaraju Mallina",
    "program": "B.Tech ME",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3001-269",
    "code": "ME3001",
    "name": "Measurement and Automation",
    "slot": "D",
    "hall": "H45",
    "faculty": "Dr. Nagaraj M",
    "program": "B.Tech ME",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3002-270",
    "code": "ME3002",
    "name": "Thermal Engineering Practice",
    "slot": "K (ME24B1001-55) / J (ME24B1056-79)",
    "hall": "L008",
    "faculty": "Dr Vikas Kumar",
    "program": "B.Tech ME",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3003-271",
    "code": "ME3003",
    "name": "Production Drawing and Inspection Practice",
    "slot": "J (ME24B1001-55) / K (ME24B1056-79)",
    "hall": "L507 / L111",
    "faculty": "Dr. Venkata Timmaraju Mallina",
    "program": "B.Tech ME",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "CS3006-272",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "E, I3-X2",
    "hall": "H45/L209+L515",
    "faculty": "Dr Pradeep Kumar",
    "program": "B.Tech SM",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "DS3000-273",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H25",
    "faculty": "Mr. Gokul R",
    "program": "B.Tech SM",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3004-274",
    "code": "ME3004",
    "name": "Operations and Supply Chain Management",
    "slot": "B",
    "hall": "H04",
    "faculty": "Dr. Shahul Hamid Khan",
    "program": "B.Tech SM",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3005-275",
    "code": "ME3005",
    "name": "Robotics and Automation",
    "slot": "D",
    "hall": "H04",
    "faculty": "Prof. Sreekumar",
    "program": "B.Tech SM",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3006-276",
    "code": "ME3006",
    "name": "Quality Engineering",
    "slot": "G, L1-L2 (ME24B21001-29) / K1-K2 (ME24B2030-55)",
    "hall": "H36/L111",
    "faculty": "Dr. K Orra",
    "program": "B.Tech SM",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3007-277",
    "code": "ME3007",
    "name": "Robotics and Automation Practice",
    "slot": "K1, K2 (ME24B21001-29) / L1, L2 (ME24B2030-55)",
    "hall": "L110",
    "faculty": "Prof. Sreekumar",
    "program": "B.Tech SM",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "DS3006-278",
    "code": "DS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "E, I3-X2",
    "hall": "H45/L209+L515",
    "faculty": "Dr Pradeep Kumar",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "DS3000-279",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H25",
    "faculty": "Mr. Gokul R",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3000-280",
    "code": "ME3000",
    "name": "Design of Machine Elements",
    "slot": "G, X3",
    "hall": "H04",
    "faculty": "Dr. Venkata Timmaraju Mallina",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3001-281",
    "code": "ME3001",
    "name": "Measurement and Automation",
    "slot": "D",
    "hall": "H45",
    "faculty": "Dr. Nagaraj M",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3002-282",
    "code": "ME3002",
    "name": "Thermal Engineering Practice",
    "slot": "J",
    "hall": "L008",
    "faculty": "Dr Vikas Kumar",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME3003-283",
    "code": "ME3003",
    "name": "Production Drawing and Inspection Practice",
    "slot": "K",
    "hall": "L507 / L111",
    "faculty": "Dr. Venkata Timmaraju Mallina",
    "program": "Dual Degree ME (AI&R)",
    "semester": "Semester 5",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5000-284",
    "code": "25ME5000",
    "name": "Data Science",
    "slot": "B/K3-X4",
    "hall": "H17/L110",
    "faculty": "Dr. Kalpana P",
    "program": "B.Tech ME",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5001-285",
    "code": "25ME5001",
    "name": "Multibody System Dynamics",
    "slot": "A",
    "hall": "H04",
    "faculty": "Dr. Nagamanikandan G",
    "program": "B.Tech ME",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5002-286",
    "code": "25ME5002",
    "name": "Engineering Design with Advanced Materials",
    "slot": "G, X3",
    "hall": "H34",
    "faculty": "Dr Venkataramani",
    "program": "B.Tech ME",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5004-287",
    "code": "25ME5004",
    "name": "Multibody System Dynamics Practice",
    "slot": "J, X2",
    "hall": "L110",
    "faculty": "Dr. Nagamanikandan G",
    "program": "B.Tech ME",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5003-288",
    "code": "25ME5003",
    "name": "Structural Analysis and Design Optimization",
    "slot": "D",
    "hall": "H36",
    "faculty": "Dr. S Gowthaman",
    "program": "B.Tech ME",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5000-289",
    "code": "25ME5000",
    "name": "Data Science",
    "slot": "B/K3-X4",
    "hall": "H17/L110",
    "faculty": "Dr. Kalpana P",
    "program": "B.Tech SM",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5005-290",
    "code": "25ME5005",
    "name": "Manufacturing Systems Engineering",
    "slot": "D/L3-X5",
    "hall": "H17/L110",
    "faculty": "Dr. Kishor Kumar Gajrani",
    "program": "B.Tech SM",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5006-291",
    "code": "25ME5006",
    "name": "Manufacturing Automation",
    "slot": "E, X3",
    "hall": "H17",
    "faculty": "Dr. Kashfull Orra",
    "program": "B.Tech SM",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5007-292",
    "code": "25ME5007",
    "name": "Manufacturing Automation Practice",
    "slot": "H, X1",
    "hall": "L110",
    "faculty": "Dr. Kashfull Orra",
    "program": "B.Tech SM",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME5008-293",
    "code": "25ME5008",
    "name": "Additive and Hybrid Manufacturing Processes",
    "slot": "G/I1-I2",
    "hall": "H17/TLC",
    "faculty": "Dr. P. Pandithevan",
    "program": "B.Tech SM",
    "semester": "Semester 1",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME4000-294",
    "code": "ME4000",
    "name": "BT-ME-Summer Internship",
    "slot": "",
    "hall": "",
    "faculty": "Dr P Pandithevan",
    "program": "B.Tech ME",
    "semester": "Semester 7",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "ME4001-295",
    "code": "ME4001",
    "name": "BT-SM-Summer Internship",
    "slot": "",
    "hall": "",
    "faculty": "Dr P Pandithevan",
    "program": "B.Tech ME",
    "semester": "Semester 7",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME6000-296",
    "code": "25ME6000",
    "name": "M Tech Dissertation (MTD) Phase I (IMSD)",
    "slot": "",
    "hall": "",
    "faculty": "Dr P Pandithevan",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME6003-297",
    "code": "25ME6003",
    "name": "M Tech Dissertation (MTD) Phase I (SM)",
    "slot": "",
    "hall": "",
    "faculty": "Dr P Pandithevan",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME6001-298",
    "code": "25ME6001",
    "name": "M Tech Dissertation (MTD) Phase II (IMSD)",
    "slot": "",
    "hall": "",
    "faculty": "Dr P Pandithevan",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25ME6004-299",
    "code": "25ME6004",
    "name": "M Tech Dissertation (MTD) Phase II (SM)",
    "slot": "",
    "hall": "",
    "faculty": "Dr P Pandithevan",
    "program": "B.Tech ME",
    "semester": "Semester 3",
    "sourceFile": "ME_Aug 2026.xlsx"
  },
  {
    "id": "25MA1002-cse-0",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H21",
    "faculty": "Dr.\u00a0Nachiketa Mishra",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25MA1002-cse-1",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H22",
    "faculty": "Prof. Shalu M A",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2000-cse-2",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G / L3 X5",
    "hall": "H44 / L512, L209",
    "faculty": "Dr Jagadeesh K",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2001-cse-3",
    "code": "25CS2001",
    "name": "Object Oriented Programming",
    "slot": "F (Except Wed) / H, X1",
    "hall": "H15 / L509",
    "faculty": "Prof. B Sivaselvan",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2002-cse-4",
    "code": "25CS2002",
    "name": "Digital Systems Design",
    "slot": "A / J3, X3",
    "hall": "H01 / L515",
    "faculty": "Dr K Kannadasan",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2003-cse-5",
    "code": "25CS2003",
    "name": "Design & Analysis of Algorithms",
    "slot": "C (Fri), B / Thu D & B",
    "hall": "H25 / L509",
    "faculty": "Dr Syed Shahul Hameed",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2004-cse-6",
    "code": "25CS2004",
    "name": "Database Systems Design",
    "slot": "C (Tue), D / Wed D & B",
    "hall": "H15 / L512",
    "faculty": "Dr M Ratna Raju",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2005-cse-7",
    "code": "25CS2005",
    "name": "Computing Paradigms",
    "slot": "C (Wed & Thur)",
    "hall": "H15",
    "faculty": "Dr Preeth",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25MA1002-cse-8",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H22",
    "faculty": "Prof. Shalu M A",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2000-cse-9",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G / L3 X5",
    "hall": "H44 / L512, L209",
    "faculty": "Dr Jagadeesh K",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2000-cse-10",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G / Wed A & F",
    "hall": "H15 / L509, L507",
    "faculty": "Dr Preeth",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2001-cse-11",
    "code": "25CS2001",
    "name": "Object Oriented Programming",
    "slot": "F (Except Wed) / H, X1",
    "hall": "H15 / L509",
    "faculty": "Prof. B Sivaselvan",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2001-cse-12",
    "code": "25CS2001",
    "name": "Object Oriented Programming",
    "slot": "F (Except Wed) / H, X1",
    "hall": "H15 / L512",
    "faculty": "Dr B Sivaselvan + Dr NSG",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2002-cse-13",
    "code": "25CS2002",
    "name": "Digital Systems Design",
    "slot": "A / J3, X3",
    "hall": "H01 / L515",
    "faculty": "Dr K Kannadasan",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2002-cse-14",
    "code": "25CS2002",
    "name": "Digital Systems Design",
    "slot": "A (Except Wed) / J1, J2",
    "hall": "H15 / L515",
    "faculty": "Dr B Krishna Priya",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2003-cse-15",
    "code": "25CS2003",
    "name": "Design & Analysis of Algorithms",
    "slot": "C (Fri), B / Thu D & B",
    "hall": "H25 / L509",
    "faculty": "Dr Syed Shahul Hameed",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2003-cse-16",
    "code": "25CS2003",
    "name": "Design & Analysis of Algorithms",
    "slot": "C (Tue), D / Wed D & B",
    "hall": "H15 / L509",
    "faculty": "Dr Syed Shahul Hameed",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2004-cse-17",
    "code": "25CS2004",
    "name": "Database Systems Design",
    "slot": "C (Tue), D / Wed D & B",
    "hall": "H15 / L512",
    "faculty": "Dr M Ratna Raju",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2004-cse-18",
    "code": "25CS2004",
    "name": "Database Systems Design",
    "slot": "C (Fri), B / Thu D & B",
    "hall": "H25 / L512",
    "faculty": "Dr M Ratna Raju",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2005-cse-19",
    "code": "25CS2005",
    "name": "Computing Paradigms",
    "slot": "C (Wed & Thur)",
    "hall": "H15",
    "faculty": "Dr Preeth",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2005-cse-20",
    "code": "25CS2005",
    "name": "Computing Paradigms",
    "slot": "C (Wed & Thur)",
    "hall": "H25",
    "faculty": "Dr Raghavan",
    "program": "B.Tech CSE",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25MA1002-cse-21",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H22",
    "faculty": "Prof. Shalu M A",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25MA1002-cse-22",
    "code": "25MA1002",
    "name": "Linear Algebra",
    "slot": "E",
    "hall": "H23",
    "faculty": "Dr. Subhasis Ghora",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2000-cse-23",
    "code": "25CS2000",
    "name": "Introduction to AI with Python",
    "slot": "G / Wed A & F",
    "hall": "H15 / L509",
    "faculty": "Dr Preeth",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2001-cse-24",
    "code": "25CS2001",
    "name": "Object Oriented Programming",
    "slot": "F (Except Wed) / H, X1",
    "hall": "H15 / L512",
    "faculty": "Dr B Sivaselvan + Dr NSG",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2002-cse-25",
    "code": "25CS2002",
    "name": "Digital Systems Design",
    "slot": "A (Except Wed) / J1, J2",
    "hall": "H15 / L515",
    "faculty": "Dr B Krishna Priya",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2003-cse-26",
    "code": "25CS2003",
    "name": "Design & Analysis of Algorithms",
    "slot": "C (Tue), D / Wed D & B",
    "hall": "H15 / L509",
    "faculty": "Dr Syed Shahul Hameed",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2004-cse-27",
    "code": "25CS2004",
    "name": "Database Systems Design",
    "slot": "C (Fri), B / Thu D & B",
    "hall": "H25 / L512",
    "faculty": "Dr M Ratna Raju",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS2005-cse-28",
    "code": "25CS2005",
    "name": "Computing Paradigms",
    "slot": "C (Wed & Thur)",
    "hall": "H25",
    "faculty": "Dr Raghavan",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 3",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3006-cse-29",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "E / L1, L2",
    "hall": "H44 / L509",
    "faculty": "Dr Jagadeesh K",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "DS3000-cse-30",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H01",
    "faculty": "Dr. Siddhant",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "DS3000-cse-31",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H02",
    "faculty": "Dr. Sadhasivam",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3000-cse-32",
    "code": "CS3000",
    "name": "Operating Systems",
    "slot": "B",
    "hall": "H41",
    "faculty": "Dr Raghavan",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3001-cse-33",
    "code": "CS3001",
    "name": "Computer Networks",
    "slot": "D",
    "hall": "H41",
    "faculty": "Dr Sanjeet Kumar Nayak",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3002-cse-34",
    "code": "CS3002",
    "name": "Compiler Design",
    "slot": "G, X1",
    "hall": "H41",
    "faculty": "Dr Mailthilee",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3003-cse-35",
    "code": "CS3003",
    "name": "Operating Systems practice",
    "slot": "J, X3",
    "hall": "L509",
    "faculty": "Dr Raghavan",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3004-cse-36",
    "code": "CS3004",
    "name": "Computers Networks practice",
    "slot": "I, X2",
    "hall": "L509",
    "faculty": "Dr Sanjeet Kumar Nayak",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3005-cse-37",
    "code": "CS3005",
    "name": "Compiler Design Practice",
    "slot": "K, X4",
    "hall": "L509",
    "faculty": "Dr Maithilee",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3007-cse-38",
    "code": "CS3007",
    "name": "Pattern Recognition and Machine Learning",
    "slot": "F / L3, X5",
    "hall": "H41 / L509",
    "faculty": "Dr J Umarani",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "DS3000-cse-39",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H02",
    "faculty": "Dr. Sadhasivam",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3000-cse-40",
    "code": "CS3000",
    "name": "Operating Systems",
    "slot": "B",
    "hall": "H41",
    "faculty": "Dr Raghavan",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3000-cse-41",
    "code": "CS3000",
    "name": "Operating Systems",
    "slot": "B",
    "hall": "H44",
    "faculty": "Dr K Rajesh",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3001-cse-42",
    "code": "CS3001",
    "name": "Computer Networks",
    "slot": "D",
    "hall": "H41",
    "faculty": "Dr Sanjeet Kumar Nayak",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3001-cse-43",
    "code": "CS3001",
    "name": "Computer Networks",
    "slot": "D",
    "hall": "H44",
    "faculty": "Dr K Gnanambikai",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3002-cse-44",
    "code": "CS3002",
    "name": "Compiler Design",
    "slot": "G, X1",
    "hall": "H41",
    "faculty": "Dr Maithilee",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3002-cse-45",
    "code": "CS3002",
    "name": "Compiler Design",
    "slot": "G, X1",
    "hall": "H42",
    "faculty": "Dr Om Prakash",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3003-cse-46",
    "code": "CS3003",
    "name": "Operating Systems practice",
    "slot": "J, X3",
    "hall": "L509",
    "faculty": "Dr Raghavan",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3003-cse-47",
    "code": "CS3003",
    "name": "Operating Systems practice",
    "slot": "J, X3",
    "hall": "L512",
    "faculty": "Dr K Rajesh",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3004-cse-48",
    "code": "CS3004",
    "name": "Computers Networks practice",
    "slot": "I, X2",
    "hall": "L509",
    "faculty": "Dr Sanjeet Kumar Nayak",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3004-cse-49",
    "code": "CS3004",
    "name": "Computers Networks practice",
    "slot": "I, X2",
    "hall": "L512",
    "faculty": "Dr K Gnanambikai",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3005-cse-50",
    "code": "CS3005",
    "name": "Compiler Design Practice",
    "slot": "K, X4",
    "hall": "L509",
    "faculty": "Dr Maithilee",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3005-cse-51",
    "code": "CS3005",
    "name": "Compiler Design Practice",
    "slot": "K, X4",
    "hall": "L512",
    "faculty": "Dr Om Prakash",
    "program": "B.Tech CSE",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3006-cse-52",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "E / L1, L2",
    "hall": "H44 / L509, L512",
    "faculty": "Dr Jagadeesh K",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3006-cse-53",
    "code": "CS3006",
    "name": "Introduction to Data Science for Engineers",
    "slot": "E / L1, L2",
    "hall": "H42 / L512, L507",
    "faculty": "Dr S Vijaya Kumar",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "DS3000-cse-54",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H02",
    "faculty": "Dr. Sadhasivam",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "DS3000-cse-55",
    "code": "DS3000",
    "name": "Entrepreneurship and Management Functions",
    "slot": "H",
    "hall": "H04",
    "faculty": "Dr. Sudhir V",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3000-cse-56",
    "code": "CS3000",
    "name": "Operating Systems",
    "slot": "B",
    "hall": "H44",
    "faculty": "Dr K Rajesh",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3001-cse-57",
    "code": "CS3001",
    "name": "Computer Networks",
    "slot": "D",
    "hall": "H44",
    "faculty": "Dr K Gnanambikai",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3002-cse-58",
    "code": "CS3002",
    "name": "Compiler Design",
    "slot": "G, X1",
    "hall": "H42",
    "faculty": "Dr Om Prakash",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3003-cse-59",
    "code": "CS3003",
    "name": "Operating Systems practice",
    "slot": "J, X3",
    "hall": "L512",
    "faculty": "Dr K Rajesh",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3004-cse-60",
    "code": "CS3004",
    "name": "Computers Networks practice",
    "slot": "I, X2",
    "hall": "L512",
    "faculty": "Dr K Gnanambikai",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3005-cse-61",
    "code": "CS3005",
    "name": "Compiler Design Practice",
    "slot": "K, X4",
    "hall": "L512",
    "faculty": "Dr Om Prakash",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 5",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS5010-cse-62",
    "code": "CS5010",
    "name": "Analytics and Systems of Big Data",
    "slot": "B / K1, K2",
    "hall": "H01 / L515",
    "faculty": "Prof. B Sivaselvan",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 7",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS5011-cse-63",
    "code": "CS5011",
    "name": "Information Security",
    "slot": "G, X3",
    "hall": "H13",
    "faculty": "Dr Sanjeet Kumar Nayak",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 7",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS5012-cse-64",
    "code": "CS5012",
    "name": "Interactive Computer Graphics",
    "slot": "E / K3, X4",
    "hall": "H01 / L209",
    "faculty": "Dr Nishanth Kartheek",
    "program": "Dual Degree CSE (AI)",
    "semester": "Semester 7",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS5000-cse-65",
    "code": "25CS5000",
    "name": "Mathematical Foundations of Computer Science",
    "slot": "D",
    "hall": "H13",
    "faculty": "Dr N Sadagopan",
    "program": "M.Tech CSE",
    "semester": "Semester 1",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS5001-cse-66",
    "code": "25CS5001",
    "name": "Advanced Data Strucures & Algorithms",
    "slot": "A X7",
    "hall": "H41",
    "faculty": "Dr Pandiri Venkatesh",
    "program": "M.Tech CSE",
    "semester": "Semester 1",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS5002-cse-67",
    "code": "25CS5002",
    "name": "Analaytics & Systems of Big Data",
    "slot": "B",
    "hall": "H01",
    "faculty": "Prof. B Sivaselvan",
    "program": "M.Tech CSE",
    "semester": "Semester 1",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS5004-cse-68",
    "code": "25CS5004",
    "name": "Advanced Data Strucures & Algorithms Practice",
    "slot": "H, X1",
    "hall": "L515",
    "faculty": "Dr Pandiri Venkatesh",
    "program": "M.Tech CSE",
    "semester": "Semester 1",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS5003-cse-69",
    "code": "25CS5003",
    "name": "Analytics & Systems of Big Data Practice",
    "slot": "K, X4",
    "hall": "L515",
    "faculty": "Prof. B Sivaselvan",
    "program": "M.Tech CSE",
    "semester": "Semester 1",
    "sourceFile": "CSE_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS5001-el-70",
    "code": "25CS5001",
    "name": "Advanced Data Structure and Algorithms",
    "slot": "A (Except Friday) X7",
    "hall": "H41",
    "faculty": "Dr Pandiri Venkatesh",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25CS5002-el-71",
    "code": "25CS5002",
    "name": "Analytics and Systems of Big Data",
    "slot": "B",
    "hall": "H01",
    "faculty": "Dr B Sivaselvan",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS5105-el-72",
    "code": "CS5105",
    "name": "Machine Learning",
    "slot": "F X10/ L3, X5",
    "hall": "H01 / L515",
    "faculty": "Dr Rahul Raman",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS6102-el-73",
    "code": "CS6102",
    "name": "Computer Architecture",
    "slot": "A (Except Friday) / J1, J2",
    "hall": "H42 / L515",
    "faculty": "Dr Shak Noor Mahammad",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS5012-el-74",
    "code": "CS5012",
    "name": "Interactive Computer Graphics",
    "slot": "E / K3, X4",
    "hall": "H01 / L209",
    "faculty": "Dr Nishanth Kartheek",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS3007-el-75",
    "code": "CS3007",
    "name": "Pattern Recognition and Machine Learning",
    "slot": "F / L3, X5",
    "hall": "H41 / L509",
    "faculty": "Dr Umarani",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS6103-el-76",
    "code": "CS6103",
    "name": "Computer Network Security",
    "slot": "C / L1, L2",
    "hall": "H42 / L209",
    "faculty": "Dr Pradeep Kumar",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS5100-el-77",
    "code": "CS5100",
    "name": "Computer Vision",
    "slot": "C (Except Friday) / Fri C & A",
    "hall": "H41 / L509",
    "faculty": "Dr V Masilamani",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "CS5109-el-78",
    "code": "CS5109",
    "name": "Brain Computer Interface",
    "slot": "C / L1, L2",
    "hall": "H01 / L515",
    "faculty": "Dr Kannadasan K",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25EC5010-el-79",
    "code": "25EC5010",
    "name": "Advanced EMFT",
    "slot": "E, X3",
    "hall": "H43",
    "faculty": "Dr Yuvaraj",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25EC5009-el-80",
    "code": "25EC5009",
    "name": "Advanced Microwave Engineering",
    "slot": "G, X5",
    "hall": "H14",
    "faculty": "Dr Sreenath Reddy",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "EC5014-el-81",
    "code": "EC5014",
    "name": "Digital IC Design",
    "slot": "A",
    "hall": "H16",
    "faculty": "Dr Binsu J Kailath",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "EC5028-el-82",
    "code": "EC5028",
    "name": "Mathematics for Communication",
    "slot": "A",
    "hall": "H14",
    "faculty": "Dr Badri",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "EC5029-el-83",
    "code": "EC5029",
    "name": "Modeling and Simulation",
    "slot": "C, H",
    "hall": "H14,L211",
    "faculty": "Dr Premkumar K",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "EC5030-el-84",
    "code": "EC5030",
    "name": "Data Communication Networks",
    "slot": "G, X5",
    "hall": "H16",
    "faculty": "Dr R Sri Prakash",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "EC4100-el-85",
    "code": "EC4100",
    "name": "RF and Microwave Circuit Design",
    "slot": "C",
    "hall": "H11",
    "faculty": "Dr Sreenath Reddy",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "EC5101-el-86",
    "code": "EC5101",
    "name": "Introduction to Photonics",
    "slot": "C",
    "hall": "H12",
    "faculty": "Dr Srijith",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "ID6100-el-87",
    "code": "ID6100",
    "name": "Energy Harvesting Technology",
    "slot": "F, X4",
    "hall": "H16",
    "faculty": "Dr Pandiyarasan Veluswamy",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "EC5107-el-88",
    "code": "EC5107",
    "name": "Medical Imaging Systems",
    "slot": "A",
    "hall": "H43",
    "faculty": "Dr Uttam Pal",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "EC5105-el-89",
    "code": "EC5105",
    "name": "Biosignal Processing and Analysis",
    "slot": "F, X4",
    "hall": "H43",
    "faculty": "Dr Rohini",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "ME5127-el-90",
    "code": "ME5127",
    "name": "Multiscale Modeling of Materials using Machine Learning",
    "slot": "F, X4",
    "hall": "H36",
    "faculty": "Arul Kumar M",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25ME5000-el-91",
    "code": "25ME5000",
    "name": "Data Science (Only for PhD)",
    "slot": "B/H1,H2",
    "hall": "H17/L110",
    "faculty": "Kalpana P",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25ME5005-el-92",
    "code": "25ME5005",
    "name": "Manufacturing Systems Engineering",
    "slot": "D/L3, X5",
    "hall": "H17/L507",
    "faculty": "Kishor Kumar Gajrani",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25ME5008-el-93",
    "code": "25ME5008",
    "name": "Additive and Hybrid Manufacturing Processes",
    "slot": "G/J1, J2",
    "hall": "H17/TLC",
    "faculty": "P. Pandithevan",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "ME5113-el-94",
    "code": "ME5113",
    "name": "Gas Dynamics and Propulsive Systems",
    "slot": "C",
    "hall": "H17",
    "faculty": "Dr. Shubhankar Chakraborty",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "ME5124-el-95",
    "code": "ME5124",
    "name": "Vibration Control",
    "slot": "A",
    "hall": "H17",
    "faculty": "Dr. Venkatramani",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "ME5103-el-96",
    "code": "ME5103",
    "name": "Design of Heat Exchangers",
    "slot": "F, X4",
    "hall": "H34",
    "faculty": "Dr. S. Jayavel",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25ME5001-el-97",
    "code": "25ME5001",
    "name": "Multibody System Dynamics",
    "slot": "E, X1",
    "hall": "H04",
    "faculty": "Nagamanikandan G",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25ME5003-el-98",
    "code": "25ME5003",
    "name": "Structural Anaysis and Design Optimization",
    "slot": "D",
    "hall": "H36",
    "faculty": "S Gowthaman",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "25ME5002-el-99",
    "code": "25ME5002",
    "name": "Engineering Design with Advanced Materials",
    "slot": "G, X3",
    "hall": "H34",
    "faculty": "Dr. Venkatramani",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "ME5114-el-100",
    "code": "ME5114",
    "name": "Thermal Turbomachines",
    "slot": "A",
    "hall": "H13",
    "faculty": "Vikash Kumar",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "DS5105-el-101",
    "code": "DS5105",
    "name": "Model based design and manufacturing",
    "slot": "A",
    "hall": "A",
    "faculty": "Dr. Rajnish & Dr. Sudhir V",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "DS5107-el-102",
    "code": "DS5107",
    "name": "Design of non-invasive systems",
    "slot": "C",
    "hall": "H13",
    "faculty": "Dr. Bingi & Dr. Anudeep",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "DS5106-el-103",
    "code": "DS5106",
    "name": "Simulation Driven Design",
    "slot": "F",
    "hall": "L407B",
    "faculty": "Dr. Raguraman",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "DS5104-el-104",
    "code": "DS5104",
    "name": "Wearable Technologies",
    "slot": "A",
    "hall": "H12",
    "faculty": "Dr. Karthic G",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "PH5102-el-105",
    "code": "PH5102",
    "name": "Materials Fabrication and Characterization Techniques",
    "slot": "C",
    "hall": "H41",
    "faculty": "Dr. Y. Ashok Kumar Reddy",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  },
  {
    "id": "MA6102-el-106",
    "code": "MA6102",
    "name": "Algebraic Number Theory (Only for PhD)",
    "slot": "B",
    "hall": "H13",
    "faculty": "Dr Jagannath Bhanja",
    "program": "Electives & Minors",
    "semester": "Semester 3",
    "sourceFile": "Electives_Aug 2026_Updated.xlsx"
  }
];
